### ISSUE TITLE
Compilation error when the positioning library is used without motion support

### ISSUE THREAD

**Issue by JulieJeannier** [wirepas/wm-sdk#32]
Hi,
I get an error when I try to add the positioning app in a custom app without motion support. 
In poslib_decode.c file, the #ifdef MOTION_SUPPORTED is missing on the motion.h file inclusion.
I'm working on version 1.2.1.
Best regards,
Julie

**Comment by GwendalRaoul** [comment]
Hello
Thanks for reporting it.
It should now be fixed in new v1.2.2 release.
Best regards,
Gwendal
